// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2L9hCuMqFA6xYDgKyhGrtm
// Component: v4hszgxO9peNm
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_test_react.module.css"; // plasmic-import: 2L9hCuMqFA6xYDgKyhGrtm/projectcss
import sty from "./PlasmicBtn.module.css"; // plasmic-import: v4hszgxO9peNm/css

export const PlasmicBtn__VariantProps = new Array("type", "behavior");

export const PlasmicBtn__ArgProps = new Array("children");

function PlasmicBtn__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootbehavior_hug]: hasVariant(variants, "behavior", "hug"),
          [sty.rootbehavior_stretch]: hasVariant(
            variants,
            "behavior",
            "stretch"
          ),

          [sty.roottype_primary]: hasVariant(variants, "type", "primary"),
          [sty.roottype_primary_behavior_hug]:
            hasVariant(variants, "type", "primary") &&
            hasVariant(variants, "behavior", "hug"),
          [sty.roottype_secondary]: hasVariant(variants, "type", "secondary")
        }
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Resume",
          value: args.children,
          className: classNames(sty.slotTargetChildren, {
            [sty.slotTargetChildrenbehavior_stretch]: hasVariant(
              variants,
              "behavior",
              "stretch"
            ),

            [sty.slotTargetChildrentype_primary]: hasVariant(
              variants,
              "type",
              "primary"
            ),

            [sty.slotTargetChildrentype_secondary]: hasVariant(
              variants,
              "type",
              "secondary"
            )
          })
        })}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBtn__ArgProps,
      internalVariantPropNames: PlasmicBtn__VariantProps
    });

    return PlasmicBtn__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBtn";
  } else {
    func.displayName = `PlasmicBtn.${nodeName}`;
  }
  return func;
}

export const PlasmicBtn = Object.assign(
  // Top-level PlasmicBtn renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicBtn
    internalVariantProps: PlasmicBtn__VariantProps,
    internalArgProps: PlasmicBtn__ArgProps
  }
);

export default PlasmicBtn;
/* prettier-ignore-end */
