// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2L9hCuMqFA6xYDgKyhGrtm
// Component: rlPwLBdmyIaRnn
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_test_react.module.css"; // plasmic-import: 2L9hCuMqFA6xYDgKyhGrtm/projectcss
import sty from "./PlasmicBottomPage.module.css"; // plasmic-import: rlPwLBdmyIaRnn/css

export const PlasmicBottomPage__VariantProps = new Array();

export const PlasmicBottomPage__ArgProps = new Array();

function PlasmicBottomPage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Ulysse Ducamp - Developped with Plasmic - Last update in March 2022"}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBottomPage__ArgProps,
      internalVariantPropNames: PlasmicBottomPage__VariantProps
    });

    return PlasmicBottomPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBottomPage";
  } else {
    func.displayName = `PlasmicBottomPage.${nodeName}`;
  }
  return func;
}

export const PlasmicBottomPage = Object.assign(
  // Top-level PlasmicBottomPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicBottomPage
    internalVariantProps: PlasmicBottomPage__VariantProps,
    internalArgProps: PlasmicBottomPage__ArgProps
  }
);

export default PlasmicBottomPage;
/* prettier-ignore-end */
