// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2L9hCuMqFA6xYDgKyhGrtm
// Component: D3qVyYHMUzh6J2
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: I6xI5GMEjQdNix/component
import Container from "../../Container"; // plasmic-import: DD1KhTcTagclR/component
import ProjectPart from "../../ProjectPart"; // plasmic-import: zn8FoPHtQ06VfQ/component
import Btn from "../../Btn"; // plasmic-import: v4hszgxO9peNm/component
import BottomPage from "../../BottomPage"; // plasmic-import: rlPwLBdmyIaRnn/component
import { useScreenVariants as useScreenVariantsqCm1ILxl7thTbv } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qCm1iLXL7thTBV/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_test_react.module.css"; // plasmic-import: 2L9hCuMqFA6xYDgKyhGrtm/projectcss
import sty from "./PlasmicProjectsLexy.module.css"; // plasmic-import: D3qVyYHMUzh6J2/css

export const PlasmicProjectsLexy__VariantProps = new Array();

export const PlasmicProjectsLexy__ArgProps = new Array();

function PlasmicProjectsLexy__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqCm1ILxl7thTbv()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__nmZrM)}
          >
            {true ? (
              <Navbar
                className={classNames("__wab_instance", sty.navbar__hT3Wo)}
              />
            ) : null}
            {true ? (
              <Navbar
                className={classNames("__wab_instance", sty.navbar___0TjoU)}
              />
            ) : null}

            <Container
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames("__wab_instance", sty.container)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__pwQ5K)}
              >
                <div
                  data-plasmic-name={"spacer2"}
                  data-plasmic-override={overrides.spacer2}
                  className={classNames(projectcss.all, sty.spacer2)}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nNwY)}
                  displayHeight={"400px"}
                  displayMaxHeight={"600vh"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/test_react/images/thumbnailLexyjpeg.jpeg",
                    fullWidth: 4096,
                    fullHeight: 3425,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w8Feh
                  )}
                >
                  {"Lexy, read differently"}
                </div>

                <div
                  data-plasmic-name={"spacer3"}
                  data-plasmic-override={overrides.spacer3}
                  className={classNames(projectcss.all, sty.spacer3)}
                />

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"contextColumns"}
                  data-plasmic-override={overrides.contextColumns}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.contextColumns)}
                >
                  <div
                    data-plasmic-name={"titleStack"}
                    data-plasmic-override={overrides.titleStack}
                    className={classNames(projectcss.all, sty.titleStack)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__axxQe
                      )}
                    >
                      {"Context"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"detailsColumns"}
                    data-plasmic-override={overrides.detailsColumns}
                    className={classNames(projectcss.all, sty.detailsColumns)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"row1"}
                      data-plasmic-override={overrides.row1}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.row1)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__vfDv)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__e9VzP
                          )}
                        >
                          {"Period"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kdu3U
                          )}
                        >
                          {"APRIL to JUNE 2019"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__iXIxx
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dZtdO
                          )}
                        >
                          {"Client"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wQi4B
                          )}
                        >
                          {"School project"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__lCnVt
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rBlPj
                          )}
                        >
                          {"Software "}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bjgW
                          )}
                        >
                          {"Figma, Miro, Google Suites, After Effects"}
                        </div>
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"row2"}
                      data-plasmic-override={overrides.row2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.row2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__e7IIv
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gIlMv
                          )}
                        >
                          {"Team"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__guPht
                          )}
                        >
                          {"Marie Jollivet (also product design student)"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___6RPo
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___924Pz
                          )}
                        >
                          {"Role"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wMtWh
                          )}
                        >
                          {"Product design"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___3U3M
                        )}
                      />
                    </p.Stack>

                    <div
                      data-plasmic-name={"spacer5"}
                      data-plasmic-override={overrides.spacer5}
                      className={classNames(projectcss.all, sty.spacer5)}
                    />
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"briefColumns"}
                  data-plasmic-override={overrides.briefColumns}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.briefColumns)}
                >
                  <div
                    data-plasmic-name={"titleStack2"}
                    data-plasmic-override={overrides.titleStack2}
                    className={classNames(projectcss.all, sty.titleStack2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cUcHe
                      )}
                    >
                      {"Starting\npoint"}
                    </div>
                  </div>

                  <div className={classNames(projectcss.all, sty.column__cxvU)}>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___6Yc2Q
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1T6Qi
                        )}
                      >
                        {
                          "Both thinking that reading had a lot of benefits, we did some monitoring on the relationship french had with this activity."
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fzcG
                        )}
                      >
                        {"\nWhat stood out: "}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rpSr
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul___2IgAt
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__my5Y0
                              )}
                            >
                              {
                                "french have never read as much as now because reading is more and more accessible thanks to education, e-books and and the public libraries."
                              }
                            </li>
                          </ul>
                          <React.Fragment>{""}</React.Fragment>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__gpoSj
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___4ZZwr
                              )}
                            >
                              {
                                "but a study from the Centre national du livre (national book center) shows that:"
                              }
                            </li>
                          </ul>
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sYrAk
                        )}
                      >
                        {'\n"‍63% of french would like to read more‍‍"\n'}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__u3Ro
                        )}
                      >
                        {
                          "Reading books appears to be the second priority of the surveyed persons, if they had more free time. Interested by those statistics, we tried to figure out why so many people don't achieve to read as much as they would like. We did some monitoring and several user interviews.\n"
                        }
                      </div>

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__xrzDk)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/test_react/images/interviewjpeg.jpeg",
                          fullWidth: 1402,
                          fullHeight: 579,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__itEl9
                        )}
                      >
                        {"\nWhat stood out: "}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ntSec
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__eXuis
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li___6KK5K
                              )}
                            >
                              {
                                "Reading seems unaccessible. It seems to take a lot of time and effort. It's hard to know where to start."
                              }
                            </li>
                          </ul>
                          <React.Fragment>{""}</React.Fragment>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__xlfZb
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                projectcss.__wab_text,
                                sty.li__uH7W7
                              )}
                            >
                              {
                                "There are too many distractions, reading books requires focus, it's hard to stick on a text when there are so many entertainment alternatives."
                              }
                            </li>
                          </ul>
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bK3Z2
                        )}
                      >
                        {
                          "\nThanks to our research we defined the problem we wanted to solve.\n\nBoth thinking that reading had a lot of benefits, we did some monitoring on the relationship french had with this activity.‍"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cpDyr
                        )}
                      >
                        {"\nOur problematic:"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___53Tgo
                        )}
                      >
                        {
                          '\n‍"How to help people achieve their reading goals in a world where it is so easy to get distracted from them ?"'
                        }
                      </div>

                      <div
                        data-plasmic-name={"spacer11"}
                        data-plasmic-override={overrides.spacer11}
                        className={classNames(projectcss.all, sty.spacer11)}
                      />
                    </div>
                  </div>
                </p.Stack>

                <ProjectPart
                  data-plasmic-name={"process"}
                  data-plasmic-override={overrides.process}
                  className={classNames("__wab_instance", sty.process)}
                  slot={"Process"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yii6V
                    )}
                  >
                    {"Personas"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7Kjam
                    )}
                  >
                    {
                      "\nTo answer our problematic we defined three personas based on our user interviews.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__bqEmz)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/personasjpeg.jpeg",
                      fullWidth: 1681,
                      fullHeight: 371,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aWpP7
                    )}
                  >
                    {
                      "\nFor us, it was important to also design for the persons who already read lot, since they are an important source of revenue for the book industries. Thinking about the business possibilities behind our service, we made another persona, a bit less usual, for the Hachette publishing house :\n"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oJJaT
                    )}
                  >
                    {
                      "‍We believed that our service could interest a big publishing house like Hachette regarding its goals.‍\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__eVQbr)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/hachettejpeg.jpeg",
                      fullWidth: 1440,
                      fullHeight: 506,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yaXl7
                    )}
                  >
                    {"\nFeatures"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oM38
                    )}
                  >
                    {
                      "\nWe did a lot of monitoring on reading to imagined powerful features. We especially based ourselves on two books: The power of habits and Ten days to Faster Reading. Those books helped us to have a better understanding of how to create reading habits and manage your goals.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__c37Pm)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/booksjpeg.jpeg",
                      fullWidth: 1440,
                      fullHeight: 630,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ikp2K
                    )}
                  >
                    {
                      "\nWe then selected and organized our features through card sorting.\n"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bgARk
                    )}
                  >
                    {
                      "‍We decided our service to be a mobile application, since we imagined features like blocking other application's notifications for more focused reading sessions.‍"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vq0I8
                    )}
                  >
                    {"\nTree structure\n"}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cwLiI)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/treeStructurepng.png",
                      fullWidth: 1664,
                      fullHeight: 1086,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gDozl
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {"\nWe designed our application with three spaces:‍\n"}
                      </React.Fragment>
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__gg1O
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__xOef0
                          )}
                        >
                          {
                            "Discover: a place to discover new books with section‍"
                          }
                        </li>

                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__jRwX
                          )}
                        >
                          {
                            "Current reading‍: the interface that enable you to read your book.‍"
                          }
                        </li>

                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__eLmPd
                          )}
                        >
                          {
                            "My space: an area where you can manage your readings."
                          }
                        </li>
                      </ul>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0PoWu
                    )}
                  >
                    {"\nUser paths\n"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3CMmb
                    )}
                  >
                    {"We defined 2 happy user paths for our main personas\n"}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__jtGie)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/userPathpng.png",
                      fullWidth: 2296,
                      fullHeight: 1022,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sOqHs
                    )}
                  >
                    {"\nIdentity\n"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__s0Mbz
                    )}
                  >
                    {
                      "We made the wireframes for the two user journeys and work on the app identity to finally produce the UI.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__qyGtu)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/visualDesignjpeg.jpeg",
                      fullWidth: 1309,
                      fullHeight: 812,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cYaSh
                    )}
                  >
                    {"\nUI design\n"}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__xsEs9)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/uiDesignpng.png",
                      fullWidth: 1464,
                      fullHeight: 1200,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    data-plasmic-name={"spacer10"}
                    data-plasmic-override={overrides.spacer10}
                    className={classNames(projectcss.all, sty.spacer10)}
                  />
                </ProjectPart>

                <ProjectPart
                  data-plasmic-name={"result"}
                  data-plasmic-override={overrides.result}
                  className={classNames("__wab_instance", sty.result)}
                  slot={"Result"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gkLpc
                    )}
                  >
                    {
                      "We designed a mobile application that helps people to achieve their reading goals by:"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4Hekc
                    )}
                  >
                    {
                      "\nOffering relevant content to enhance our user's interest for literature\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__n9KPk)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/screenContentjpeg.jpeg",
                      fullWidth: 3934,
                      fullHeight: 2460,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eM32O
                    )}
                  >
                    {
                      "\nProposing different ways to read each book to improve their reading experience \n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__jl4W)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/screenModesjpeg.jpeg",
                      fullWidth: 3934,
                      fullHeight: 2460,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rImYu
                    )}
                  >
                    {
                      "\nAllowing a better management of their readings with the possibility to schedule reading sessions directly from the app\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___6DxG)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/screenAgendajpeg.jpeg",
                      fullWidth: 3660,
                      fullHeight: 2288,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eGpEv
                    )}
                  >
                    {
                      "\nEnabling our user to see their progress through their statistics and offering them rewards to keep their motivation high.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__jwzNw)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/screenDatajpeg.jpeg",
                      fullWidth: 3660,
                      fullHeight: 2288,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    data-plasmic-name={"spacer9"}
                    data-plasmic-override={overrides.spacer9}
                    className={classNames(projectcss.all, sty.spacer9)}
                  />
                </ProjectPart>
              </p.Stack>
            </Container>

            <Container
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              background={"bgblack"}
              className={classNames("__wab_instance", sty.footer)}
            >
              <div
                data-plasmic-name={"footerStack"}
                data-plasmic-override={overrides.footerStack}
                className={classNames(projectcss.all, sty.footerStack)}
                id={"Footer"}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"footerColumns"}
                  data-plasmic-override={overrides.footerColumns}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.footerColumns)}
                >
                  <div
                    data-plasmic-name={"card"}
                    data-plasmic-override={overrides.card}
                    className={classNames(projectcss.all, sty.card)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__xkxBi)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___98T6)}
                        displayHeight={"350px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/test_react/images/thumbnailCollabjpeg.jpeg",
                          fullWidth: 1280,
                          fullHeight: 837,
                          aspectRatio: undefined
                        }}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bvGwc
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pcGj1
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{"Collab, "}</React.Fragment>
                            <span
                              data-plasmic-name={"span"}
                              data-plasmic-override={overrides.span}
                              className={classNames(
                                projectcss.all,
                                projectcss.span,
                                projectcss.__wab_text,
                                projectcss.plasmic_default__inline,
                                sty.span
                              )}
                            >
                              {
                                "enhancing communication between teachers and students"
                              }
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nqxcD
                          )}
                        >
                          {
                            "A feature for a university intranet that merges features imagined to facilitate the life of teachers, students and other important school's actors."
                          }
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hV5H
                          )}
                        >
                          <p.PlasmicLink
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__ifVzW
                            )}
                            component={Link}
                            href={"/projects/collab"}
                            platform={"nextjs"}
                          >
                            <Btn
                              data-plasmic-name={"btn"}
                              data-plasmic-override={overrides.btn}
                              behavior={"stretch"}
                              className={classNames("__wab_instance", sty.btn)}
                              type={"secondary"}
                            >
                              {"View project"}
                            </Btn>
                          </p.PlasmicLink>
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"ctaColumn"}
                    data-plasmic-override={overrides.ctaColumn}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.ctaColumn)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ytvnJ
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "I am currently looking for a new internship to conclude my studies. Starting in June."
                        : "I am currently looking for a new internship to conclude my studies. Starting in June."}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pl2C
                      )}
                    >
                      {"feel free to contact me at :"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__j3LjG
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__kr6Dk
                          )}
                          component={Link}
                          href={"mailto:name@email.com"}
                          platform={"nextjs"}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ textDecorationLine: "underline" }}
                            >
                              {"u.ducamp@lecolededesign.com"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </p.PlasmicLink>
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__v3HAy
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"(or through "}</React.Fragment>
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__euZxw
                          )}
                          component={Link}
                          href={
                            "https://www.linkedin.com/in/ulysse-ducamp-3752b413b/"
                          }
                          platform={"nextjs"}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ textDecorationLine: "underline" }}
                            >
                              {"my Linkedin"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </p.PlasmicLink>
                        <React.Fragment>{")"}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </p.Stack>
                </p.Stack>
              </div>
            </Container>

            <BottomPage
              data-plasmic-name={"bottomPage"}
              data-plasmic-override={overrides.bottomPage}
              className={classNames("__wab_instance", sty.bottomPage)}
            />
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "container",
    "spacer2",
    "spacer3",
    "contextColumns",
    "titleStack",
    "detailsColumns",
    "row1",
    "row2",
    "spacer5",
    "briefColumns",
    "titleStack2",
    "spacer11",
    "process",
    "spacer10",
    "result",
    "spacer9",
    "footer",
    "footerStack",
    "footerColumns",
    "card",
    "span",
    "btn",
    "ctaColumn",
    "bottomPage"
  ],

  container: [
    "container",
    "spacer2",
    "spacer3",
    "contextColumns",
    "titleStack",
    "detailsColumns",
    "row1",
    "row2",
    "spacer5",
    "briefColumns",
    "titleStack2",
    "spacer11",
    "process",
    "spacer10",
    "result",
    "spacer9"
  ],

  spacer2: ["spacer2"],
  spacer3: ["spacer3"],
  contextColumns: [
    "contextColumns",
    "titleStack",
    "detailsColumns",
    "row1",
    "row2",
    "spacer5"
  ],

  titleStack: ["titleStack"],
  detailsColumns: ["detailsColumns", "row1", "row2", "spacer5"],
  row1: ["row1"],
  row2: ["row2"],
  spacer5: ["spacer5"],
  briefColumns: ["briefColumns", "titleStack2", "spacer11"],
  titleStack2: ["titleStack2"],
  spacer11: ["spacer11"],
  process: ["process", "spacer10"],
  spacer10: ["spacer10"],
  result: ["result", "spacer9"],
  spacer9: ["spacer9"],
  footer: [
    "footer",
    "footerStack",
    "footerColumns",
    "card",
    "span",
    "btn",
    "ctaColumn"
  ],

  footerStack: [
    "footerStack",
    "footerColumns",
    "card",
    "span",
    "btn",
    "ctaColumn"
  ],

  footerColumns: ["footerColumns", "card", "span", "btn", "ctaColumn"],
  card: ["card", "span", "btn"],
  span: ["span"],
  btn: ["btn"],
  ctaColumn: ["ctaColumn"],
  bottomPage: ["bottomPage"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProjectsLexy__ArgProps,
      internalVariantPropNames: PlasmicProjectsLexy__VariantProps
    });

    return PlasmicProjectsLexy__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjectsLexy";
  } else {
    func.displayName = `PlasmicProjectsLexy.${nodeName}`;
  }
  return func;
}

export const PlasmicProjectsLexy = Object.assign(
  // Top-level PlasmicProjectsLexy renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    container: makeNodeComponent("container"),
    spacer2: makeNodeComponent("spacer2"),
    spacer3: makeNodeComponent("spacer3"),
    contextColumns: makeNodeComponent("contextColumns"),
    titleStack: makeNodeComponent("titleStack"),
    detailsColumns: makeNodeComponent("detailsColumns"),
    row1: makeNodeComponent("row1"),
    row2: makeNodeComponent("row2"),
    spacer5: makeNodeComponent("spacer5"),
    briefColumns: makeNodeComponent("briefColumns"),
    titleStack2: makeNodeComponent("titleStack2"),
    spacer11: makeNodeComponent("spacer11"),
    process: makeNodeComponent("process"),
    spacer10: makeNodeComponent("spacer10"),
    result: makeNodeComponent("result"),
    spacer9: makeNodeComponent("spacer9"),
    footer: makeNodeComponent("footer"),
    footerStack: makeNodeComponent("footerStack"),
    footerColumns: makeNodeComponent("footerColumns"),
    card: makeNodeComponent("card"),
    span: makeNodeComponent("span"),
    btn: makeNodeComponent("btn"),
    ctaColumn: makeNodeComponent("ctaColumn"),
    bottomPage: makeNodeComponent("bottomPage"),
    // Metadata about props expected for PlasmicProjectsLexy
    internalVariantProps: PlasmicProjectsLexy__VariantProps,
    internalArgProps: PlasmicProjectsLexy__ArgProps
  }
);

export default PlasmicProjectsLexy;
/* prettier-ignore-end */
