// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2L9hCuMqFA6xYDgKyhGrtm
// Component: Fpmgd2F96f9no
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: I6xI5GMEjQdNix/component
import Container from "../../Container"; // plasmic-import: DD1KhTcTagclR/component
import ProjectPart from "../../ProjectPart"; // plasmic-import: zn8FoPHtQ06VfQ/component
import Btn from "../../Btn"; // plasmic-import: v4hszgxO9peNm/component
import BottomPage from "../../BottomPage"; // plasmic-import: rlPwLBdmyIaRnn/component
import { useScreenVariants as useScreenVariantsqCm1ILxl7thTbv } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qCm1iLXL7thTBV/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_test_react.module.css"; // plasmic-import: 2L9hCuMqFA6xYDgKyhGrtm/projectcss
import sty from "./PlasmicProjectsCollab.module.css"; // plasmic-import: Fpmgd2F96f9no/css

export const PlasmicProjectsCollab__VariantProps = new Array();

export const PlasmicProjectsCollab__ArgProps = new Array();

function PlasmicProjectsCollab__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqCm1ILxl7thTbv()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__lwmay)}
          >
            {true ? (
              <Navbar
                className={classNames("__wab_instance", sty.navbar__zhWzl)}
              />
            ) : null}
            {true ? (
              <Navbar
                className={classNames("__wab_instance", sty.navbar__vjgFc)}
              />
            ) : null}

            <Container
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames("__wab_instance", sty.container)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__c2Uu5)}
              >
                <div
                  data-plasmic-name={"spacer2"}
                  data-plasmic-override={overrides.spacer2}
                  className={classNames(projectcss.all, sty.spacer2)}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__aNhpS)}
                  displayHeight={"400px"}
                  displayMaxHeight={"600vh"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/test_react/images/_5F36B63155Cd1A7669789751CouvAgendajpeg2.jpeg",
                    fullWidth: 1280,
                    fullHeight: 837,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tddv8
                  )}
                >
                  {
                    "Collab, enhancing communication between teachers and students"
                  }
                </div>

                <div
                  data-plasmic-name={"spacer3"}
                  data-plasmic-override={overrides.spacer3}
                  className={classNames(projectcss.all, sty.spacer3)}
                />

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"contextColumns"}
                  data-plasmic-override={overrides.contextColumns}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.contextColumns)}
                >
                  <div
                    data-plasmic-name={"titleStack"}
                    data-plasmic-override={overrides.titleStack}
                    className={classNames(projectcss.all, sty.titleStack)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dp14
                      )}
                    >
                      {"Context"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"detailsColumns"}
                    data-plasmic-override={overrides.detailsColumns}
                    className={classNames(projectcss.all, sty.detailsColumns)}
                  >
                    <div
                      data-plasmic-name={"row1"}
                      data-plasmic-override={overrides.row1}
                      className={classNames(projectcss.all, sty.row1)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ib013
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ip4Qf
                          )}
                        >
                          {"Period"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__m6MgU
                          )}
                        >
                          {"MARCH to JUNE 2020"}
                        </div>
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__aJbY)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nrL2G
                          )}
                        >
                          {"Client"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mZ9Gp
                          )}
                        >
                          {"Our school, as a client"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__lEwtU
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nwmYd
                          )}
                        >
                          {"Software "}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dVTx
                          )}
                        >
                          {"Adobe XD, Miro, Notion, Zoom, Loom"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"row2"}
                      data-plasmic-override={overrides.row2}
                      className={classNames(projectcss.all, sty.row2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__pxvUq
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fns7H
                          )}
                        >
                          {"Team"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o52Vi
                          )}
                        >
                          {"Jeanne Verstreate (also product design student)"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___6L6Tr
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gRuWn
                          )}
                        >
                          {"Role"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zplak
                          )}
                        >
                          {"Product design"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___9JsmT
                        )}
                      />
                    </div>

                    <div
                      data-plasmic-name={"spacer5"}
                      data-plasmic-override={overrides.spacer5}
                      className={classNames(projectcss.all, sty.spacer5)}
                    />
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"briefColumns"}
                  data-plasmic-override={overrides.briefColumns}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.briefColumns)}
                >
                  <div
                    data-plasmic-name={"titleStack2"}
                    data-plasmic-override={overrides.titleStack2}
                    className={classNames(projectcss.all, sty.titleStack2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3FdIi
                      )}
                    >
                      {"Brief"}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__aqBvx)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0ZoIr
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3St22
                        )}
                      >
                        {
                          "This project was in partnership with our own school, L'École de design Nantes Atlantique. The goal of the school through this partnership was to make us design new ways to take advantage of digital into our learning process.\n\nHere is a part of the brief that we focused on:"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5NyD
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{"\n"}</React.Fragment>
                          <span
                            className={classNames(
                              projectcss.all,
                              projectcss.span,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.span__bFiMu
                            )}
                          >
                            {'"'}
                          </span>
                          <React.Fragment>
                            {
                              "L'École de design's intranet has been completely redesigned in 2018. This space can be a base for new reflections regarding the classes construction."
                            }
                          </React.Fragment>
                          <span
                            className={classNames(
                              projectcss.all,
                              projectcss.span,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.span__c46Hn
                            )}
                          >
                            {'"'}
                          </span>
                          <React.Fragment>{"\n"}</React.Fragment>
                        </React.Fragment>
                      </div>

                      <div
                        data-plasmic-name={"spacer11"}
                        data-plasmic-override={overrides.spacer11}
                        className={classNames(projectcss.all, sty.spacer11)}
                      />
                    </div>
                  </div>
                </p.Stack>

                <ProjectPart
                  data-plasmic-name={"process"}
                  data-plasmic-override={overrides.process}
                  className={classNames("__wab_instance", sty.process)}
                  slot={"Process"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wkoRs
                    )}
                  >
                    {"Phase 1, Exploring/defining"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7Kjam
                    )}
                  >
                    {
                      "\nTo understand the context and its users but also to see in which direction we can go as digital designers, we did a lot of monitoring and several user interviews.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__bqEmz)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabinterviewpng.png",
                      fullWidth: 2098,
                      fullHeight: 1054,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pJbIf
                    )}
                  >
                    {"\nWhat stood out: "}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tj3EW
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__o1LCp
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__emowb
                          )}
                        >
                          {
                            "digital content allows more efficiency in the learning process but requires more self-discipline."
                          }
                        </li>
                      </ul>
                      <React.Fragment>{""}</React.Fragment>
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__tvnBv
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__p1J8W
                          )}
                        >
                          {
                            "digital can help to participate more. for example thanks to quiz or video projects. "
                          }
                        </li>

                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__w9Yv3
                          )}
                        >
                          {
                            "It is easy for a student to get loose in a course and to lack of involvement during the classes."
                          }
                        </li>
                      </ul>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__msDiu
                    )}
                  >
                    {"That's how we came up with our problematic."}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fm0DD
                    )}
                  >
                    {"\nOur problematic:"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iRe7
                    )}
                  >
                    {
                      '‍\n"How to get school\'s actors more involved into the students learning process thanks to digital?"‍\n'
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tskY7
                    )}
                  >
                    {
                      "To us it was important to design our product not only for the students but also for the other actors of the school. We had the idea that the more parts of the school we would involved, the more impact our service would have."
                    }
                  </div>

                  <div
                    data-plasmic-name={"spacer8"}
                    data-plasmic-override={overrides.spacer8}
                    className={classNames(projectcss.all, sty.spacer8)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3Hl7
                    )}
                  >
                    {"\nPhase 2, Ideation/structure"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zlzQv
                    )}
                  >
                    {
                      "\nTo answer our problematic, we needed more background. We did 5 other interviews to have a better understanding of the everyday life of our users.From those interviews we defined personas that allowed us to make experience maps and finally user journeys.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__t0Lal)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabconceptualisationpng.png",
                      fullWidth: 2370,
                      fullHeight: 1142,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hjnSb
                    )}
                  >
                    {
                      "\nWe finally kept 3 happy journeys imagined for 3 user types:\n "
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x54Dj
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul___8AvuB
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__q5WaI
                          )}
                        >
                          {"Student"}
                        </li>
                      </ul>
                      <React.Fragment>{""}</React.Fragment>
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul___09Rt7
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__w9LvV
                          )}
                        >
                          {"Teacher "}
                        </li>

                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__rwarj
                          )}
                        >
                          {
                            "Business Service employee (in charge of making the link between our school and the professional world)"
                          }
                        </li>
                      </ul>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vkBT
                    )}
                  >
                    {"\nSelecting the product's features (card sorting)\n"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nyKou
                    )}
                  >
                    {
                      "To answer our problematic, we needed more background. We did 5 other interviews to have a better understanding of the everyday life of our users.From those interviews we defined personas that allowed us to make experience maps and finally user journeys.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__acV9)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabcardSortingpng.png",
                      fullWidth: 2336,
                      fullHeight: 564,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___91LDa
                    )}
                  >
                    {"\nThe problem we were facing: "}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gHcTj
                    )}
                  >
                    {
                      "\nWe had a lot of features that seemed interesting but we did not know how to make them live in a single one and sharp product.\n"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lQ7N2
                    )}
                  >
                    {
                      "Every feature seems to play an important role, yet, it was hard to make the links between all of our features. We didn't wanted to make a category per feature, it was crucial to us that our features could be used with the less friction possible..‍"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hqMpX
                    )}
                  >
                    {"\nThe solution: "}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rvPo
                    )}
                  >
                    {
                      "\n‍‍The school calendar as the center of all our features‍\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__yFroK)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabcalendarpng.png",
                      fullWidth: 2216,
                      fullHeight: 1044,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t9Thd
                    )}
                  >
                    {"\nWhy ? \n"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5Uoev
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      <ul
                        className={classNames(
                          projectcss.all,
                          projectcss.ul,
                          sty.ul__evXgV
                        )}
                      >
                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li__yPwm
                          )}
                        >
                          {
                            "Because it's a tool that our user target already used everyday."
                          }
                        </li>

                        <li
                          className={classNames(
                            projectcss.all,
                            projectcss.li,
                            projectcss.__wab_text,
                            sty.li___82SLv
                          )}
                        >
                          {
                            "Because we had the intuition that the school's calendar could be a good base for all our features."
                          }
                        </li>
                      </ul>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>

                  <div
                    data-plasmic-name={"spacer7"}
                    data-plasmic-override={overrides.spacer7}
                    className={classNames(projectcss.all, sty.spacer7)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d9RfA
                    )}
                  >
                    {"\nPhase 3, Production/iteration"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vdh7J
                    )}
                  >
                    {"\nThe process we did follow for the phase 3: \n"}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___7MqLg)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabprocessjpeg.jpeg",
                      fullWidth: 4096,
                      fullHeight: 885,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dmxbE
                    )}
                  >
                    {
                      "\nDoing user tests with low-fidelity prototypes allowed us to refine easily our product before starting more engaging prototype work.‍\n"
                    }
                  </div>

                  <div
                    data-plasmic-name={"spacer10"}
                    data-plasmic-override={overrides.spacer10}
                    className={classNames(projectcss.all, sty.spacer10)}
                  />
                </ProjectPart>

                <ProjectPart
                  data-plasmic-name={"result"}
                  data-plasmic-override={overrides.result}
                  className={classNames("__wab_instance", sty.result)}
                  slot={"Result"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9Wng
                    )}
                  >
                    {
                      "We designed a responsive agenda that make class management easier for the teacher, the student but also the business service of the school (the service in charge of making the link between our school and the professional world).‍"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eroVa
                    )}
                  >
                    {"\nThe teacher:"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jbTFu
                    )}
                  >
                    {
                      "\nHe can understand how much work students have and set a realistic deadline for his courses project.\n"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vKkIq
                    )}
                  >
                    {
                      "One problem that teachers told us about is that it is hard for them to set a deadline because they have no visibility on the work quantity that their pupils have. They loose time rescheduling their deadline because they realize their students have to much work on a specific period.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ksWnx)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabscreen1Jpeg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ntutm
                    )}
                  >
                    {
                      "\nThanks to the 2 weeks view and the red tags for the delivery, he can easily view deliveries his students have already to do and consciously define a deadline.‍"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__m0Su5
                    )}
                  >
                    {
                      "\nHe can create quiz, launch them and see their results through any of the courses events.\n "
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fcQro
                    )}
                  >
                    {
                      "Simplifying the process of doing questionnaires was crucial to us. It allows a better support of the pupils. Thanks to our Quiz feature, It's easier for the teacher to notice the students who have difficulties and on which part of the course.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__dmFrL)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabscreen2Jpeg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ew8Vf
                    )}
                  >
                    {"\nHe can also upload resources.\n"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eT8KB
                    )}
                  >
                    {
                      "Thanks to that feature, when the teacher sees that some of his pupils have difficulties with certain notion, he can easily share some resources to help them review the notions. By this way everyone stay involved.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__gQnf3)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabscreen3Jpeg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fj6Sj
                    )}
                  >
                    {
                      '\nWe defined 3 categories of resources : "Classes" for the resources that have been shared in class, "To review notions" for resources that explain notions already seen in class and "to go further".‍‍\n'
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uGCyF
                    )}
                  >
                    {"\nThe student:"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iwPll
                    )}
                  >
                    {
                      "\nAll the elements related to the course are reunited in a single place."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gH68A
                    )}
                  >
                    {
                      "\nThrough any event of the course, the student have access to the ressources, the quizz added by the teacher, the brief of the courses project, etc. It is easier for him to be up to date.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__dznV)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabscreen4Jpeg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cBusi
                    )}
                  >
                    {"\nHe can easily communicate with his teacher\n"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1WtyO
                    )}
                  >
                    {
                      "\nThe student can ask a question to the teacher thanks to the chat area. The exchange will be then viewable by all the class so the teacher doesn't have to repeat himself.‍\n"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xqg0D
                    )}
                  >
                    {"\nThe Business services employee:"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__o7L
                    )}
                  >
                    {
                      "\nThanks to the filter panel at the top, the business services employee can see the deliveries of a specific students group.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__npKtE)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabscreen5Jpeg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__j66Z8
                    )}
                  >
                    {
                      "\nThen, with the right panel, he can see the details of the project that will be delivered and estimates if it's interesting for him to assist to the delivery. He can also ask the students to deliver a synthesis pdf page so he can then have an overview of each project.\n"
                    }
                  </div>

                  <div
                    data-plasmic-name={"spacer9"}
                    data-plasmic-override={overrides.spacer9}
                    className={classNames(projectcss.all, sty.spacer9)}
                  />
                </ProjectPart>

                <ProjectPart
                  data-plasmic-name={"projectPart"}
                  data-plasmic-override={overrides.projectPart}
                  className={classNames("__wab_instance", sty.projectPart)}
                  slot={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pvEKq
                      )}
                    >
                      {"Technical\naspect"}
                    </div>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nV4Ue
                    )}
                  >
                    {
                      "We tried to make our style guide as simple as possible for more consistency and an easier development.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__rgL4M)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabGuIjpeg.jpeg",
                      fullWidth: 2279,
                      fullHeight: 1513,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fF6Zi
                    )}
                  >
                    {
                      "\nWe made our user interface following a grid of 4. Each margin and size are a multiple of 4 : 4px, 8px, 12px, 16px, 20px, etc.\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__tpy7Z)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabgridjpeg.jpeg",
                      fullWidth: 1568,
                      fullHeight: 835,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__daR8
                    )}
                  >
                    {"\nA responsive service, from computer to Iphone 5.\n "}
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__nciWf)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabCalldavpng.png",
                      fullWidth: 1760,
                      fullHeight: 794,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__h3Zb6
                    )}
                  >
                    {"\nAnd even more responsiveness: "}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1ZGw0
                    )}
                  >
                    {
                      "\nThe Caldav Protocol is a protocol that allows a calendar to be sync with multiple calendar applications. It is thanks to this protocol that you can see your agenda no matter your calendar app (google, apple, fantastical calendar, etc.)\n"
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cGtN
                    )}
                  >
                    {
                      "\nOn the screenshot below, you can see that thanks to the Caldav protocol, the users can enjoy our service even in their personal calendar app (here, Apple Calendar).\n"
                    }
                  </div>

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__solt)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/collabapplecaljpg.jpeg",
                      fullWidth: 2560,
                      fullHeight: 1600,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    data-plasmic-name={"spacer12"}
                    data-plasmic-override={overrides.spacer12}
                    className={classNames(projectcss.all, sty.spacer12)}
                  />
                </ProjectPart>
              </p.Stack>
            </Container>

            <Container
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              background={"bgblack"}
              className={classNames("__wab_instance", sty.footer)}
            >
              <div
                data-plasmic-name={"footerStack"}
                data-plasmic-override={overrides.footerStack}
                className={classNames(projectcss.all, sty.footerStack)}
                id={"Footer"}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"footerColumns"}
                  data-plasmic-override={overrides.footerColumns}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.footerColumns)}
                >
                  <div
                    data-plasmic-name={"card"}
                    data-plasmic-override={overrides.card}
                    className={classNames(projectcss.all, sty.card)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__wm3Wi)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__a0PqN)}
                        displayHeight={"350px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/test_react/images/thumbnailLexyjpeg.jpeg",
                          fullWidth: 4096,
                          fullHeight: 3425,
                          aspectRatio: undefined
                        }}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__wSt78
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lq7Sj
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{"Lexy, "}</React.Fragment>
                            <span
                              className={classNames(
                                projectcss.all,
                                projectcss.span,
                                projectcss.__wab_text,
                                projectcss.plasmic_default__inline,
                                sty.span__oz7
                              )}
                            >
                              {"read differently"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___4CQd
                          )}
                        >
                          {
                            "A mobile app designed to help poeple achieve their reading goals in a word where it’s so easy to get distracted from them."
                          }
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oxHiH
                          )}
                        >
                          <p.PlasmicLink
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__omAt2
                            )}
                            component={Link}
                            href={"/projects/collab-2"}
                            platform={"nextjs"}
                          >
                            <Btn
                              data-plasmic-name={"btn"}
                              data-plasmic-override={overrides.btn}
                              behavior={"stretch"}
                              className={classNames("__wab_instance", sty.btn)}
                              type={"secondary"}
                            >
                              {"View project"}
                            </Btn>
                          </p.PlasmicLink>
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </div>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"ctaColumn"}
                    data-plasmic-override={overrides.ctaColumn}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.ctaColumn)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lawBq
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "I am currently looking for a new internship to conclude my studies. Starting in June."
                        : "I am currently looking for a new internship to conclude my studies. Starting in June."}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a69M1
                      )}
                    >
                      {"feel free to contact me at :"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dElF4
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__sMx1J
                          )}
                          component={Link}
                          href={"mailto:name@email.com"}
                          platform={"nextjs"}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ textDecorationLine: "underline" }}
                            >
                              {"u.ducamp@lecolededesign.com"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </p.PlasmicLink>
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0MPv8
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"(or through "}</React.Fragment>
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__wJdpM
                          )}
                          component={Link}
                          href={
                            "https://www.linkedin.com/in/ulysse-ducamp-3752b413b/"
                          }
                          platform={"nextjs"}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ textDecorationLine: "underline" }}
                            >
                              {"my Linkedin"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </p.PlasmicLink>
                        <React.Fragment>{")"}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </p.Stack>
                </p.Stack>
              </div>
            </Container>

            <BottomPage
              data-plasmic-name={"bottomPage"}
              data-plasmic-override={overrides.bottomPage}
              className={classNames("__wab_instance", sty.bottomPage)}
            />
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "container",
    "spacer2",
    "spacer3",
    "contextColumns",
    "titleStack",
    "detailsColumns",
    "row1",
    "row2",
    "spacer5",
    "briefColumns",
    "titleStack2",
    "spacer11",
    "process",
    "spacer8",
    "spacer7",
    "spacer10",
    "result",
    "spacer9",
    "projectPart",
    "spacer12",
    "footer",
    "footerStack",
    "footerColumns",
    "card",
    "btn",
    "ctaColumn",
    "bottomPage"
  ],

  container: [
    "container",
    "spacer2",
    "spacer3",
    "contextColumns",
    "titleStack",
    "detailsColumns",
    "row1",
    "row2",
    "spacer5",
    "briefColumns",
    "titleStack2",
    "spacer11",
    "process",
    "spacer8",
    "spacer7",
    "spacer10",
    "result",
    "spacer9",
    "projectPart",
    "spacer12"
  ],

  spacer2: ["spacer2"],
  spacer3: ["spacer3"],
  contextColumns: [
    "contextColumns",
    "titleStack",
    "detailsColumns",
    "row1",
    "row2",
    "spacer5"
  ],

  titleStack: ["titleStack"],
  detailsColumns: ["detailsColumns", "row1", "row2", "spacer5"],
  row1: ["row1"],
  row2: ["row2"],
  spacer5: ["spacer5"],
  briefColumns: ["briefColumns", "titleStack2", "spacer11"],
  titleStack2: ["titleStack2"],
  spacer11: ["spacer11"],
  process: ["process", "spacer8", "spacer7", "spacer10"],
  spacer8: ["spacer8"],
  spacer7: ["spacer7"],
  spacer10: ["spacer10"],
  result: ["result", "spacer9"],
  spacer9: ["spacer9"],
  projectPart: ["projectPart", "spacer12"],
  spacer12: ["spacer12"],
  footer: [
    "footer",
    "footerStack",
    "footerColumns",
    "card",
    "btn",
    "ctaColumn"
  ],

  footerStack: ["footerStack", "footerColumns", "card", "btn", "ctaColumn"],
  footerColumns: ["footerColumns", "card", "btn", "ctaColumn"],
  card: ["card", "btn"],
  btn: ["btn"],
  ctaColumn: ["ctaColumn"],
  bottomPage: ["bottomPage"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProjectsCollab__ArgProps,
      internalVariantPropNames: PlasmicProjectsCollab__VariantProps
    });

    return PlasmicProjectsCollab__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProjectsCollab";
  } else {
    func.displayName = `PlasmicProjectsCollab.${nodeName}`;
  }
  return func;
}

export const PlasmicProjectsCollab = Object.assign(
  // Top-level PlasmicProjectsCollab renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    container: makeNodeComponent("container"),
    spacer2: makeNodeComponent("spacer2"),
    spacer3: makeNodeComponent("spacer3"),
    contextColumns: makeNodeComponent("contextColumns"),
    titleStack: makeNodeComponent("titleStack"),
    detailsColumns: makeNodeComponent("detailsColumns"),
    row1: makeNodeComponent("row1"),
    row2: makeNodeComponent("row2"),
    spacer5: makeNodeComponent("spacer5"),
    briefColumns: makeNodeComponent("briefColumns"),
    titleStack2: makeNodeComponent("titleStack2"),
    spacer11: makeNodeComponent("spacer11"),
    process: makeNodeComponent("process"),
    spacer8: makeNodeComponent("spacer8"),
    spacer7: makeNodeComponent("spacer7"),
    spacer10: makeNodeComponent("spacer10"),
    result: makeNodeComponent("result"),
    spacer9: makeNodeComponent("spacer9"),
    projectPart: makeNodeComponent("projectPart"),
    spacer12: makeNodeComponent("spacer12"),
    footer: makeNodeComponent("footer"),
    footerStack: makeNodeComponent("footerStack"),
    footerColumns: makeNodeComponent("footerColumns"),
    card: makeNodeComponent("card"),
    btn: makeNodeComponent("btn"),
    ctaColumn: makeNodeComponent("ctaColumn"),
    bottomPage: makeNodeComponent("bottomPage"),
    // Metadata about props expected for PlasmicProjectsCollab
    internalVariantProps: PlasmicProjectsCollab__VariantProps,
    internalArgProps: PlasmicProjectsCollab__ArgProps
  }
);

export default PlasmicProjectsCollab;
/* prettier-ignore-end */
