// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2L9hCuMqFA6xYDgKyhGrtm
// Component: iJe-ff47ZjPLs
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: I6xI5GMEjQdNix/component
import Btn from "../../Btn"; // plasmic-import: v4hszgxO9peNm/component
import Scroller from "../../Scroller"; // plasmic-import: wV3YVcGwShnWr/component
import Container from "../../Container"; // plasmic-import: DD1KhTcTagclR/component
import VerticalCard from "../../VerticalCard"; // plasmic-import: 5EaK3yGZLLC1K/component
import BottomPage from "../../BottomPage"; // plasmic-import: rlPwLBdmyIaRnn/component
import { useScreenVariants as useScreenVariantsqCm1ILxl7thTbv } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: qCm1iLXL7thTBV/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_test_react.module.css"; // plasmic-import: 2L9hCuMqFA6xYDgKyhGrtm/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: iJe-ff47ZjPLs/css

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsqCm1ILxl7thTbv()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"linesContainer"}
            data-plasmic-override={overrides.linesContainer}
            hasGap={true}
            className={classNames(projectcss.all, sty.linesContainer)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__r2Vd)} />

            <div className={classNames(projectcss.all, sty.freeBox__ateHm)} />

            <div className={classNames(projectcss.all, sty.freeBox__mQxsn)} />
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___9HkeC)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <div
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              className={classNames(projectcss.all, sty.hero)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__wvqv1)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qi3Hg
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                    <React.Fragment>
                      <React.Fragment>{"Welcome,\n\nI am a "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#3A94FF" }}
                      >
                        {"UX-UI/product design"}
                      </span>
                      <React.Fragment>
                        {" student\n\ncurrently working at "}
                      </React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ textDecorationLine: "underline" }}
                      >
                        {"Tooly"}
                      </span>
                      <React.Fragment>{" in Montreal."}</React.Fragment>
                    </React.Fragment>
                  ) : (
                    <React.Fragment>
                      <React.Fragment>{"Welcome,\nI am a "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#3A94FF" }}
                      >
                        {"UX-UI/product design"}
                      </span>
                      <React.Fragment>
                        {" student\ncurrently working at "}
                      </React.Fragment>
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__jrz0
                        )}
                        component={Link}
                        href={
                          "https://www.linkedin.com/company/tooly/?originalSubdomain=ca"
                        }
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ textDecorationLine: "underline" }}
                          >
                            {"Tooly"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </p.PlasmicLink>
                      <React.Fragment>{" in Montreal."}</React.Fragment>
                    </React.Fragment>
                  )}
                </div>

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ub71H
                    )}
                  >
                    {
                      "Now looking for a new internship to conclude my studies. Starting in June."
                    }
                  </div>
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__l7AP)}
                  >
                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__hyvWd
                      )}
                      component={Link}
                      href={"#Footer"}
                      id={""}
                      platform={"nextjs"}
                    >
                      <Btn
                        behavior={"hug"}
                        className={classNames("__wab_instance", sty.btn__xdy4Z)}
                        type={"primary"}
                      >
                        {"View my email"}
                      </Btn>
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      data-plasmic-name={"linklinkedin"}
                      data-plasmic-override={overrides.linklinkedin}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.linklinkedin
                      )}
                      component={Link}
                      href={
                        "https://www.linkedin.com/in/ulysse-ducamp-3752b413b/"
                      }
                      platform={"nextjs"}
                      target={"_blank"}
                    >
                      <Btn
                        className={classNames("__wab_instance", sty.btn__llBhg)}
                        type={"secondary"}
                      >
                        {"View my Linkedin"}
                      </Btn>
                    </p.PlasmicLink>
                  </p.Stack>
                ) : null}
              </p.Stack>
            </div>

            <Scroller
              className={classNames("__wab_instance", sty.scroller__ljl7E)}
            />
          </p.Stack>

          <Container
            className={classNames("__wab_instance", sty.container__qqAjH)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"cardsContainer"}
              data-plasmic-override={overrides.cardsContainer}
              hasGap={true}
              className={classNames(projectcss.all, sty.cardsContainer)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"cardCollab"}
                data-plasmic-override={overrides.cardCollab}
                hasGap={true}
                className={classNames(projectcss.all, sty.cardCollab)}
              >
                <div className={classNames(projectcss.all, sty.column__mDYgs)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__d8Njr)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "450px"
                        : "450px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/_5F36B63155Cd1A7669789751CouvAgendajpeg.jpeg",
                      fullWidth: 1280,
                      fullHeight: 837,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__zHiIc)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__j7H0K
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#3A94FF" }}
                      >
                        {"Collab"}
                      </span>
                      <React.Fragment>
                        {
                          ", enhancing communication between teachers and students"
                        }
                      </React.Fragment>
                    </React.Fragment>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2UEf
                    )}
                  >
                    {
                      "A feature for a university intranet that merges features imagined to facilitate the life of teachers, students and other important school's actors."
                    }
                  </div>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__ypAiu
                    )}
                    component={Link}
                    href={"/projects/collab"}
                    platform={"nextjs"}
                  >
                    <Btn
                      className={classNames("__wab_instance", sty.btn__dHHe)}
                      type={"secondary"}
                    >
                      {"View project"}
                    </Btn>
                  </p.PlasmicLink>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"cardLexy"}
                data-plasmic-override={overrides.cardLexy}
                hasGap={true}
                className={classNames(projectcss.all, sty.cardLexy)}
              >
                <div className={classNames(projectcss.all, sty.column__g5Eut)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___4TNc)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "450px"
                        : "450px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/test_react/images/_5F510D503C096D46Dfbe75F0Coverjpeg.jpeg",
                      fullWidth: 4096,
                      fullHeight: 3425,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"details"}
                  data-plasmic-override={overrides.details}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.details)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l5QnW
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#3A94FF" }}
                      >
                        {"Lexy"}
                      </span>
                      <React.Fragment>{", read differently"}</React.Fragment>
                    </React.Fragment>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gG7UI
                    )}
                  >
                    {
                      "A mobile app designed to help people achieve their reading goals in a world where it is so easy to get distracted from them"
                    }
                  </div>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__lyDi
                    )}
                    component={Link}
                    href={"/projects/collab-2"}
                    platform={"nextjs"}
                  >
                    <Btn
                      className={classNames("__wab_instance", sty.btn__z27At)}
                      type={"secondary"}
                    >
                      {"View project"}
                    </Btn>
                  </p.PlasmicLink>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </Container>

          <Container
            data-plasmic-name={"divider"}
            data-plasmic-override={overrides.divider}
            className={classNames("__wab_instance", sty.divider)}
          >
            <div
              data-plasmic-name={"spacer"}
              data-plasmic-override={overrides.spacer}
              className={classNames(projectcss.all, sty.spacer)}
            />
          </Container>

          <Container
            className={classNames("__wab_instance", sty.container__i9F0K)}
          >
            <Scroller
              className={classNames("__wab_instance", sty.scroller__r8G6X)}
            >
              {"Work\nExperience"}
            </Scroller>
          </Container>

          <Container
            data-plasmic-name={"divider2"}
            data-plasmic-override={overrides.divider2}
            className={classNames("__wab_instance", sty.divider2)}
          >
            <div
              data-plasmic-name={"spacer2"}
              data-plasmic-override={overrides.spacer2}
              className={classNames(projectcss.all, sty.spacer2)}
            />
          </Container>

          <Container
            data-plasmic-name={"workContainer"}
            data-plasmic-override={overrides.workContainer}
            className={classNames("__wab_instance", sty.workContainer)}
          >
            <div
              data-plasmic-name={"workStack"}
              data-plasmic-override={overrides.workStack}
              className={classNames(projectcss.all, sty.workStack)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pjOLu
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    data-plasmic-name={"span"}
                    data-plasmic-override={overrides.span}
                    className={classNames(
                      projectcss.all,
                      projectcss.span,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.span
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#3A94FF" }}
                      >
                        {"Three internships"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </span>
                  <React.Fragment>{""}</React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#3A94FF" }}
                  >
                    {","}
                  </span>
                  <React.Fragment>
                    {" three different structures"}
                  </React.Fragment>
                </React.Fragment>
              </div>

              <div
                data-plasmic-name={"spacer3"}
                data-plasmic-override={overrides.spacer3}
                className={classNames(projectcss.all, sty.spacer3)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"workComlums"}
                data-plasmic-override={overrides.workComlums}
                hasGap={true}
                className={classNames(projectcss.all, sty.workComlums)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"jujotte"}
                  data-plasmic-override={overrides.jujotte}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.jujotte)}
                >
                  <VerticalCard
                    className={classNames(
                      "__wab_instance",
                      sty.verticalCard__xt2D6
                    )}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yn05
                        )}
                      >
                        {"Digital design agency"}
                      </div>
                    }
                    slot2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8Djbo
                        )}
                      >
                        {"From Sept to Nov 2019"}
                      </div>
                    }
                    slot3={
                      (
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6AYFb
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{"Roles : \n"}</React.Fragment>
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul___9KXsC
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__meann
                                )}
                              >
                                {"Prototyping of a B2B software"}
                              </li>
                            </ul>
                            <React.Fragment>{""}</React.Fragment>
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__tKQv8
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__gj8C
                                )}
                              >
                                {
                                  "Designed canvas for circular design workshops"
                                }
                              </li>
                            </ul>
                            <React.Fragment>{""}</React.Fragment>
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__h2TwK
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__aVdiO
                                )}
                              >
                                {"Designed comunication"}
                              </li>
                            </ul>
                            <React.Fragment>{""}</React.Fragment>
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__lekO5
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__crI4Z
                                )}
                              >
                                {
                                  "Co animated design workshops for students and professionals."
                                }
                              </li>
                            </ul>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>
                      ) : null
                    }
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__s29F9)}
                      displayHeight={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "50vw"
                          : "auto"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/test_react/images/jujotteThumbnailpng.png",
                        fullWidth: 684,
                        fullHeight: 684,
                        aspectRatio: undefined
                      }}
                    />
                  </VerticalCard>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"onepoint"}
                  data-plasmic-override={overrides.onepoint}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.onepoint)}
                >
                  <VerticalCard
                    className={classNames(
                      "__wab_instance",
                      sty.verticalCard__b5AZn
                    )}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fqQCt
                        )}
                      >
                        {"Tech consulting group"}
                      </div>
                    }
                    slot2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__g4M1
                        )}
                      >
                        {"From Oct 2021 to Jan 2020"}
                      </div>
                    }
                    slot3={
                      (
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sptRn
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{"Roles: \n"}</React.Fragment>
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__mtzmi
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__a2IqY
                                )}
                              >
                                {
                                  "Did the research and the UX of a virtual reality project"
                                }
                              </li>
                            </ul>
                            <React.Fragment>{""}</React.Fragment>
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__cJb8B
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__zIaTc
                                )}
                              >
                                {
                                  "Designed a todolist feature of an internal platform"
                                }
                              </li>
                            </ul>
                            <React.Fragment>{""}</React.Fragment>
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__t8W76
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__vc0K
                                )}
                              >
                                {"Facilitated a service design project "}
                              </li>
                            </ul>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>
                      ) : null
                    }
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___47Aj5)}
                      displayHeight={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "50vw"
                          : "auto"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/test_react/images/onepointThumbnailpng.png",
                        fullWidth: 684,
                        fullHeight: 684,
                        aspectRatio: undefined
                      }}
                    />
                  </VerticalCard>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"tooly"}
                  data-plasmic-override={overrides.tooly}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.tooly)}
                >
                  <VerticalCard
                    className={classNames(
                      "__wab_instance",
                      sty.verticalCard__v8DAo
                    )}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8Cg4
                        )}
                      >
                        {"Software Start-up"}
                      </div>
                    }
                    slot2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9MFTb
                        )}
                      >
                        {"From Oct 2021 to now"}
                      </div>
                    }
                    slot3={
                      (
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? true
                          : true
                      ) ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dVesM
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{"Roles:\n"}</React.Fragment>
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__q3Z3N
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__hwuub
                                )}
                              >
                                {
                                  "Research and UX-UI design to enable users to easily build visually things for theirselves"
                                }
                              </li>
                            </ul>
                            <React.Fragment>{""}</React.Fragment>
                            <ul
                              className={classNames(
                                projectcss.all,
                                projectcss.ul,
                                sty.ul__yjhn5
                              )}
                            >
                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__ikQb3
                                )}
                              >
                                {"Software user flows design\n"}
                              </li>

                              <li
                                className={classNames(
                                  projectcss.all,
                                  projectcss.li,
                                  projectcss.__wab_text,
                                  sty.li__yt63
                                )}
                              >
                                {"Design system documentation"}
                              </li>
                            </ul>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>
                      ) : null
                    }
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___5Pd2H)}
                      displayHeight={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "50vw"
                          : "auto"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/test_react/images/toolyThumbnailpng.png",
                        fullWidth: 684,
                        fullHeight: 684,
                        aspectRatio: undefined
                      }}
                    />
                  </VerticalCard>
                </p.Stack>
              </p.Stack>
            </div>
          </Container>

          <Container
            data-plasmic-name={"divider3"}
            data-plasmic-override={overrides.divider3}
            className={classNames("__wab_instance", sty.divider3)}
          >
            <div
              data-plasmic-name={"spacer4"}
              data-plasmic-override={overrides.spacer4}
              className={classNames(projectcss.all, sty.spacer4)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4ArtJ
                )}
              >
                {"Perhaps my next work experience"}
              </div>
            </div>
          </Container>

          <Container
            background={"bgblack"}
            className={classNames("__wab_instance", sty.container__smoHu)}
          >
            <div
              data-plasmic-name={"sectionStack"}
              data-plasmic-override={overrides.sectionStack}
              className={classNames(projectcss.all, sty.sectionStack)}
            >
              <div
                data-plasmic-name={"textContainer"}
                data-plasmic-override={overrides.textContainer}
                className={classNames(projectcss.all, sty.textContainer)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__u1LA7
                  )}
                >
                  {"will be with your company?"}
                </div>
              </div>

              <div
                data-plasmic-name={"footerStack"}
                data-plasmic-override={overrides.footerStack}
                className={classNames(projectcss.all, sty.footerStack)}
                id={"Footer"}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"footerColumns"}
                  data-plasmic-override={overrides.footerColumns}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.footerColumns)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"ctaColumn"}
                    data-plasmic-override={overrides.ctaColumn}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.ctaColumn)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5EW4M
                      )}
                    >
                      {
                        "I am currently looking for a new internship to conclude my studies. Starting in June."
                      }
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__q7Tuv
                      )}
                    >
                      {"Feel free to contact me at :"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y2F1
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__kqysS
                          )}
                          component={Link}
                          href={"mailto:name@email.com"}
                          platform={"nextjs"}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ textDecorationLine: "underline" }}
                            >
                              {"u.ducamp@lecolededesign.com"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </p.PlasmicLink>
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ifBTo
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"(or through "}</React.Fragment>
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__obYqj
                          )}
                          component={Link}
                          href={
                            "https://www.linkedin.com/in/ulysse-ducamp-3752b413b/"
                          }
                          platform={"nextjs"}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ textDecorationLine: "underline" }}
                            >
                              {"my Linkedin"}
                            </span>
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </p.PlasmicLink>
                        <React.Fragment>{")"}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(projectcss.all, sty.column__vkXla)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__cCyoM)}
                      displayHeight={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "110vw"
                          : "auto"
                      }
                      displayMaxHeight={"600px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/test_react/images/ulyssejpeg.jpeg",
                        fullWidth: 2730,
                        fullHeight: 4096,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </p.Stack>
              </div>
            </div>
          </Container>

          <BottomPage
            data-plasmic-name={"bottomPage"}
            data-plasmic-override={overrides.bottomPage}
            className={classNames("__wab_instance", sty.bottomPage)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "linesContainer",
    "navbar",
    "hero",
    "linklinkedin",
    "cardsContainer",
    "cardCollab",
    "cardLexy",
    "details",
    "divider",
    "spacer",
    "divider2",
    "spacer2",
    "workContainer",
    "workStack",
    "span",
    "spacer3",
    "workComlums",
    "jujotte",
    "onepoint",
    "tooly",
    "divider3",
    "spacer4",
    "sectionStack",
    "textContainer",
    "footerStack",
    "footerColumns",
    "ctaColumn",
    "bottomPage"
  ],

  linesContainer: ["linesContainer"],
  navbar: ["navbar"],
  hero: ["hero", "linklinkedin"],
  linklinkedin: ["linklinkedin"],
  cardsContainer: ["cardsContainer", "cardCollab", "cardLexy", "details"],
  cardCollab: ["cardCollab"],
  cardLexy: ["cardLexy", "details"],
  details: ["details"],
  divider: ["divider", "spacer"],
  spacer: ["spacer"],
  divider2: ["divider2", "spacer2"],
  spacer2: ["spacer2"],
  workContainer: [
    "workContainer",
    "workStack",
    "span",
    "spacer3",
    "workComlums",
    "jujotte",
    "onepoint",
    "tooly"
  ],

  workStack: [
    "workStack",
    "span",
    "spacer3",
    "workComlums",
    "jujotte",
    "onepoint",
    "tooly"
  ],

  span: ["span"],
  spacer3: ["spacer3"],
  workComlums: ["workComlums", "jujotte", "onepoint", "tooly"],
  jujotte: ["jujotte"],
  onepoint: ["onepoint"],
  tooly: ["tooly"],
  divider3: ["divider3", "spacer4"],
  spacer4: ["spacer4"],
  sectionStack: [
    "sectionStack",
    "textContainer",
    "footerStack",
    "footerColumns",
    "ctaColumn"
  ],

  textContainer: ["textContainer"],
  footerStack: ["footerStack", "footerColumns", "ctaColumn"],
  footerColumns: ["footerColumns", "ctaColumn"],
  ctaColumn: ["ctaColumn"],
  bottomPage: ["bottomPage"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    linesContainer: makeNodeComponent("linesContainer"),
    navbar: makeNodeComponent("navbar"),
    hero: makeNodeComponent("hero"),
    linklinkedin: makeNodeComponent("linklinkedin"),
    cardsContainer: makeNodeComponent("cardsContainer"),
    cardCollab: makeNodeComponent("cardCollab"),
    cardLexy: makeNodeComponent("cardLexy"),
    details: makeNodeComponent("details"),
    divider: makeNodeComponent("divider"),
    spacer: makeNodeComponent("spacer"),
    divider2: makeNodeComponent("divider2"),
    spacer2: makeNodeComponent("spacer2"),
    workContainer: makeNodeComponent("workContainer"),
    workStack: makeNodeComponent("workStack"),
    span: makeNodeComponent("span"),
    spacer3: makeNodeComponent("spacer3"),
    workComlums: makeNodeComponent("workComlums"),
    jujotte: makeNodeComponent("jujotte"),
    onepoint: makeNodeComponent("onepoint"),
    tooly: makeNodeComponent("tooly"),
    divider3: makeNodeComponent("divider3"),
    spacer4: makeNodeComponent("spacer4"),
    sectionStack: makeNodeComponent("sectionStack"),
    textContainer: makeNodeComponent("textContainer"),
    footerStack: makeNodeComponent("footerStack"),
    footerColumns: makeNodeComponent("footerColumns"),
    ctaColumn: makeNodeComponent("ctaColumn"),
    bottomPage: makeNodeComponent("bottomPage"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
